### ISSUE TITLE
WebStorm 2020.2

### ISSUE THREAD

**Issue by karimbeyrouti** [krasa/EditorGroups#18]
Looks like the update to WebStorm 2020.2 broke your wonderful plugin. Is that an issue you are aware of, and aiming to fix ? 
Also thank you so much for this, love this plugin.

![editor-groups](https://user-images.githubusercontent.com/789754/89879234-8893a980-dbba-11ea-854b-76491d4e8de1.png)

**Comment by krasa** [comment]
Works for me. :( That refresh button does not fix it?

**Comment by karimbeyrouti** [comment]
it does not :-(

**Comment by karimbeyrouti** [comment]
Maybe it is the MaterialThemeUI (going through all my other plugins to see what could be the issue)

**Comment by karimbeyrouti** [comment]
I can see this exception in IDE errors: 

`
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key ide.mac.boldEditorTabs
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:115)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:182)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:159)
	at com.intellij.openapi.util.registry.RegistryValue.calcBoolean(RegistryValue.java:65)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:58)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:53)
	at krasa.editorGroups.tabs2.impl.JBEditorTabs.useBoldLabels(JBEditorTabs.java:74)
	at krasa.editorGroups.tabs2.impl.TabLabel.lambda$setText$0(TabLabel.java:297)
	at com.intellij.ui.SimpleColoredComponent.change(SimpleColoredComponent.java:1106)
	at krasa.editorGroups.tabs2.impl.TabLabel.setText(TabLabel.java:292)
	at krasa.editorGroups.tabs2.impl.JBTabsImpl.updateText(JBTabsImpl.java:1284)
	at krasa.editorGroups.tabs2.impl.JBTabsImpl.addTab(JBTabsImpl.java:849)
	at krasa.editorGroups.tabs2.impl.JBTabsImpl.addTabSilently(JBTabsImpl.java:824)
	at krasa.editorGroups.EditorGroupPanel.createTabs(EditorGroupPanel.java:397)
	at krasa.editorGroups.EditorGroupPanel.reloadTabs(EditorGroupPanel.java:340)
	at krasa.editorGroups.EditorGroupPanel.render2(EditorGroupPanel.java:935)
	at krasa.editorGroups.EditorGroupPanel.render(EditorGroupPanel.java:907)
	at krasa.editorGroups.EditorGroupPanel.lambda$null$0(EditorGroupPanel.java:788)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by pviegas** [comment]
Same error here

**Comment by karimbeyrouti** [comment]
That fixed it :-) thank you so much ...
