### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by SomewhatCloudy** [krasa/EditorGroups#27]
Windows 10, 
PhpStorm 2021.2 Build #PS-212.4746.100
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. 
EditorGroups (0.38)

It seems to happen when I use //@idea.title but I'm not entirely sure that this is related. The resources it accesses are also on WSL2 but I also doubt that is a problem either. Just thought I should mention it.

`java.lang.NullPointerException
	at krasa.editorGroups.model.Link.getName(Link.java:77)
	at krasa.editorGroups.UniqueTabNameBuilder.put(UniqueTabNameBuilder.java:57)
	at krasa.editorGroups.UniqueTabNameBuilder.getNamesByPath(UniqueTabNameBuilder.java:33)
	at krasa.editorGroups.EditorGroupPanel.reloadTabs(EditorGroupPanel.java:342)
	at krasa.editorGroups.EditorGroupPanel._render2(EditorGroupPanel.java:954)
	at krasa.editorGroups.EditorGroupPanel.postConstruct(EditorGroupPanel.java:284)
	at krasa.editorGroups.ProjectComponent$1.createPanel(ProjectComponent.java:71)
	at krasa.editorGroups.ProjectComponent$1.fileOpenedSync(ProjectComponent.java:54)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy88.fileOpenedSync(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:1105)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:969)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:965)
	at com.jetbrains.rdserver.editors.BackendServerFileEditorManager.openFileImpl4(BackendServerFileEditorManager.kt:63)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:891)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:890)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:731)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditorImpl$22(FileEditorManagerImpl.java:1269)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1263)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.java:1239)
	at com.intellij.openapi.fileEditor.FileEditorManager.openEditor(FileEditorManager.java:222)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInAnyFileEditor(FileNavigatorImpl.java:81)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditor(FileNavigatorImpl.java:62)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditorOrNativeApp(FileNavigatorImpl.java:47)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigate(FileNavigatorImpl.java:30)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:91)
	at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.processSelectedItem(FileSearchEverywhereContributor.java:108)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.processSelectedItem(PSIPresentationBgRendererWrapper.java:294)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI.elementsSelected(SearchEverywhereUI.java:794)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI.lambda$registerSelectItemAction$35(SearchEverywhereUI.java:684)
	at com.intellij.openapi.project.DumbAwareAction$SimpleDumbAwareAction.actionPerformed(DumbAwareAction.java:80)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:799)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

Help me Vojtěch Kenobi, you are my only hope.

**Comment by krasa** [comment]
Hello, 
Not sure what is the problem, I've made a quick fix:
[EditorGroups.zip](https://github.com/krasa/EditorGroups/files/7017976/EditorGroups.zip)
(install the whole zip)

Some particular tab will now have the full path, instead of the filename, please report it.

**Comment by krasa** [comment]
But perhaps it was just my bug and the current fix will be fine.

**Comment by SomewhatCloudy** [comment]
No more crashes now! The full path is in all files that have any form of `//@idea.related` markup, e.g...

```
//@idea.related */product-edit-slim.hbs
//@idea.related */_product-edit-slim.scss
```
Or
```
//@idea.title Editor Variation
//@idea.related */editor-variation.hbs
//@idea.related */_editor-variation.scss
```

Basically every tab with any form of markup has the issue. As I said it's on wsl2 so the paths look like /wsl$/Ubuntu/home/me/dev/etc rather than any c:\ stuff. Actually a quick test of a project on a normal c:\ partition has no issues, so it may be that?

**Comment by krasa** [comment]
Yes, thanks. I will try to fix that tomorrow.

**Comment by SomewhatCloudy** [comment]
Cheers, good luck. Give me a prod if you need something tested.

**Comment by krasa** [comment]
This might work: 
[EditorGroups.zip](https://github.com/krasa/EditorGroups/files/7021268/EditorGroups.zip)

**Comment by SomewhatCloudy** [comment]
It's still displaying the full path, and none of the tabs are really clickable. No crashes though so that's a plus!

**Comment by krasa** [comment]
Unfortunately, I currently do not have Win 10 Pro, so I cannot test it.
Please look into a log if it prints anything, even if it works.

[EditorGroups.zip](https://github.com/krasa/EditorGroups/files/7025492/EditorGroups.zip)
