### ISSUE TITLE
Plugin is crashed in Rider  version  19.2.2

### ISSUE THREAD

**Issue by SashaChoko** [krasa/EditorGroups#7]
StackTrace:
ExternalExportService.cs

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/intellij/mock/MockVirtualFile
	at krasa.editorGroups.EditorGroupPanel.getGroupInReadActionWithRetries(EditorGroupPanel.java:852)
	at krasa.editorGroups.EditorGroupPanel.refresh3(EditorGroupPanel.java:746)
	at krasa.editorGroups.EditorGroupPanel.access$1000(EditorGroupPanel.java:65)
	at krasa.editorGroups.EditorGroupPanel$8.run(EditorGroupPanel.java:723)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/intellij/mock/MockVirtualFile
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.jetbrains.concurrency.AsyncPromise.get(AsyncPromise.kt:19)
	at krasa.editorGroups.EditorGroupPanel.getGroupInReadActionWithRetries(EditorGroupPanel.java:843)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/mock/MockVirtualFile
	at krasa.editorGroups.AutoGroupProvider.getFolderGroup(AutoGroupProvider.java:47)
	at krasa.editorGroups.EditorGroupManager.getGroup(EditorGroupManager.java:169)
	at krasa.editorGroups.EditorGroupPanel$9.call(EditorGroupPanel.java:837)
	at krasa.editorGroups.EditorGroupPanel$9.call(EditorGroupPanel.java:833)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:162)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$2(NonBlockingReadActionImpl.java:140)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$6(NonBlockingReadActionImpl.java:140)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.intellij.mock.MockVirtualFile PluginClassLoader[EditorGroups, 0.28] com.intellij.ide.plugins.cl.PluginClassLoader@6c6dca22
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 20 more

--------------------------------
Following exceptions happened soon after this one, most probably they are induced.

2019-09-03T09:09:36.037
ExternalExportManager.Form.cs
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/intellij/mock/MockVirtualFile
	at krasa.editorGroups.EditorGroupPanel.getGroupInReadActionWithRetries(EditorGroupPanel.java:852)
	at krasa.editorGroups.EditorGroupPanel.refresh3(EditorGroupPanel.java:746)
	at krasa.editorGroups.EditorGroupPanel.access$1000(EditorGroupPanel.java:65)
	at krasa.editorGroups.EditorGroupPanel$8.run(EditorGroupPanel.java:723)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/intellij/mock/MockVirtualFile
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.jetbrains.concurrency.AsyncPromise.get(AsyncPromise.kt:19)
	at krasa.editorGroups.EditorGroupPanel.getGroupInReadActionWithRetries(EditorGroupPanel.java:843)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/mock/MockVirtualFile
	at krasa.editorGroups.AutoGroupProvider.getFolderGroup(AutoGroupProvider.java:47)
	at krasa.editorGroups.EditorGroupManager.getGroup(EditorGroupManager.java:169)
	at krasa.editorGroups.EditorGroupPanel$9.call(EditorGroupPanel.java:837)
	at krasa.editorGroups.EditorGroupPanel$9.call(EditorGroupPanel.java:833)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:162)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$2(NonBlockingReadActionImpl.java:140)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$6(NonBlockingReadActionImpl.java:140)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.intellij.mock.MockVirtualFile PluginClassLoader[EditorGroups, 0.28] com.intellij.ide.plugins.cl.PluginClassLoader@6c6dca22
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 20 more

**Comment by krasa** [comment]
thanks
